src/Entity/Trick.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 */
class Trick implements \JsonSerializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_create;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="tricks")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\File", mappedBy="trick_image", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $images;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\File", mappedBy="trick_video", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $videos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="trick", cascade={"persist", "remove"})
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cover;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $slug;



    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function jsonSerialize()
    {
        return array(
            'id' => $this->id,
            'picture' => $this->getCover(),
            'name' => $this->name,
            'date_create' =>  $this->date_create->format('d-m-Y'),
            'slug' => $this->getSlug(),
//            'pictureName' => $this->image->name
            );
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|File[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(File $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
//            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(File $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getTrickImage() === $this) {
                $image->setTrickImage(null);
            }
        }

        return $this;
    }

    public function setImages($image): self
    {
        $this->images = $image;
        return $this;
    }

    /**
     * @return Collection|File[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(File $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(File $video): self
    {
        if ($this->videos->contains($video)) {
            $this->videos->removeElement($video);
            // set the owning side to null (unless already changed)
            if ($video->getTrickVideo() === $this) {
                $video->setTrickVideo(null);
            }
        }

        return $this;
    }

    public function setVideos($video): self
    {
        $this->videos = $video;
        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    public function getCover()
    {
        return $this->cover;
    }

    public function setCover($cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Trick;
use App\Entity\Picture;
use App\Entity\Video;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', \Symfony\Component\Form\Extension\Core\Type\TextType::class, [
                'label' => 'Nom de la figure'
            ])
            ->add('category', EntityType::class, [
                'label' => 'Catégorie',
                'attr' => ['class' => 'mdb-select md-form colorful-select dropdown-primary'],
                'class' => Category::class,
                'choice_label' => 'name'
        ])
        ->add('images', CollectionType::class, [
            'label' => 'Images(s)',
            'entry_type' => FileType::class,
            'required'   => true,
            'entry_options' => array(
                'constraints'  => array(
                  new File(['maxSize' => '2M',
                  "maxSizeMessage" => "Votre document ne doit pas dépasser les 2 Mo.",
                  "mimeTypes" => ["image/jpeg", "image/png"],
                  "mimeTypesMessage" => "Le document doit avoir une des extensions suivantes : jpeg, png, jpg.",
                        ]),
                   ),
                ),
               'prototype_name' => '__images__',
               'prototype'      => true,
               'allow_add'     => true,
               'allow_delete'   => true,
               'required' => true,
        ])
            ->add('cover', FileType::class, [
            ])
            ->add('videos', CollectionType::class, [
            'label' => 'Video(s)',
            'entry_type' => FileType::class,
            'entry_options' => array(
                'constraints'  => array(
                  new File(['maxSize' => '10M',
                  "maxSizeMessage" => "Votre document ne doit pas dépasser les 10 Mo.",
                  "mimeTypes" => ["video/mp4", "video/3gpp"],
                  "mimeTypesMessage" => "Le document doit avoir une des extensions suivantes : mp4, 3gpp.",
                        ]),
                   ),
                ),
               'prototype_name' => '__videos__',
               'prototype'      => true,
               'allow_add'     => true,
               'allow_delete'   => true,
               'required' => true,

        ])
        ->add('description', TextareaType::class, [
        'label' => 'Description de la figure'
    ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
            'csrf_protection'   => false,

        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Trick;
use App\Entity\Picture;
use App\Entity\Video;
use App\Form\CommentType;
use App\Form\TrickEditCoverType;
use App\Form\TrickEditType;
use App\Form\TrickType;
use App\Repository\CommentRepository;
use App\Repository\TrickRepository;
use App\Services\FileManager;
use App\Services\SlugifyService;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TrickController extends AbstractController
{
    /**
     * @Route("/member/trick/new", name="trick_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileManager $filemanager, SlugifyService $slugify): Response
    {
        $trick = new Trick();
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $array_picture = array();
            $array_video = array();

            $trick->setCover($filemanager->simpleUpload($trick->getCover(), 'picture'));

            foreach ($trick->getImages() as $image):
                $picture = $filemanager->upload($image, $trick->getName(), 'picture', 'picture', 'setTrickImage', $trick);
            array_push($array_picture, $picture);
            endforeach;
            foreach ($trick->getVideos() as $vid):
                $video = $filemanager->upload($vid, $trick->getName(), 'video', 'video', 'setTrickVideo', $trick);
            array_push($array_video, $video);
            endforeach;

            $trick->setVideos($array_video);
            $trick->setImages($array_picture);


            $entityManager = $this->getDoctrine()->getManager();
            $trick->setDateCreate(new \DateTime());
            $trick->setAuthor($this->getUser());

            $trick->setSlug($slugify->generateSlugify($trick->getName(), Trick::class));



            $entityManager->persist($trick);
            $entityManager->flush();

            $this->addFlash(
                'success',
                'Le trick ' . $trick->getName() . ' a bien été enregistré !'
            );


            return $this->redirectToRoute('app_homepage_index');
        }

        return $this->render('trick/new.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/member/trick/{slug}", name="trick_show", methods={"GET", "POST"})
     * @param Trick $trick
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @param CommentRepository $commentRepository
     * @return Response
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function show(Trick $trick, Request $request, EntityManagerInterface $manager, CommentRepository $commentRepository): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setTrick($trick);
            $comment->setUser($this->getUser());
            $trick->addComment($comment);

            $manager->persist($comment);
            $manager->flush();
            return $this->redirectToRoute('trick_show', array(
                'slug' => $trick->getSlug()
            ));
        }
        return $this->render('trick/show.html.twig', [
            'compteur' => $commentRepository->count(array('trick' => $trick->getId())),
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/member/trick/{slug}/edit", name="trick_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Trick $trick): Response
    {
        $form = $this->createForm(TrickEditType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();


            return $this->redirectToRoute('trick_show', [
                'slug' => $trick->getSlug(),
            ]);
        }

        return $this->render('trick/edit.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/member/trick/{slug}/edit/cover", name="trick_edit_cover", methods={"GET","POST"})
     */
    public function editCover(Request $request, Trick $trick, FileManager $filemanager): Response
    {
        $form = $this->createForm(TrickEditCoverType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $trick->setCover($filemanager->simpleUpload($trick->getCover(), 'picture'));
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('trick_show', [
                'slug' => $trick->getSlug(),
            ]);
        }

        return $this->render('trick/edit_cover.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/member/trick/delete/{id}", name="trick_delete", methods={"DELETE"})
     */
    public function delete(FileManager $fileManager, Request $request, Trick $trick): Response
    {
        $entityManager = $this->getDoctrine()->getManager();

        foreach ($trick->getImages() as $image) {
            $fileManager->deleteFile($image);
            $trick->removeImage($image);
        }
        foreach ($trick->getVideos() as $video) {
            $fileManager->deleteFile($video);
        }
        $entityManager->remove($trick);
        $entityManager->flush();

        return $this->redirectToRoute('app_homepage_index');
    }

    /**
     * @Route("/member/trick/ajaxComment/{slug}", name="trick_comment_ajax", methods={ "POST"})
     * @param Trick $trick
     * @param Request $request
     * @param CommentRepository $commentRepository
     * @return Response
     */
    public function ajaxComment(Trick $trick, Request $request, CommentRepository $commentRepository): Response
    {
        $start = $_POST['start'];
        $id = $_POST['id'];
        return new JsonResponse($commentRepository->getComment($id, $start, 5));
    }
}

templates/trick/_delete_form.html.twig
<form method="post" action="{{ path('trick_delete', {'id': trick.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
    <button class="btn">Delete</button>
</form>

templates/trick/_form.html.twig
{{ form_start(form) }}


<div class="container">
	<div class="row">
		<div class="col">
			{{ form_label(form.name) }}
			{{ form_widget(form.name) }}
			{{ form_errors(form.name) }}
		</div>
		<div class="col">
			{{ form_label(form.category) }}
			{{ form_widget(form.category) }}
			{{ form_errors(form.category) }}
		</div>
	</div>
	<div class="row">
		<div class="col">
			{{ form_label(form.description) }}
			{{ form_widget(form.description) }}
			{{ form_errors(form.description) }}
		</div>
	</div>
	<div class="row">
		<div class="col">
			{{ form_label(form.cover) }}
			{{ form_widget(form.cover) }}
			{{ form_errors(form.cover) }}
		</div>
	</div>
	<div class="row">
		<div class="col">
			{{ form_label(form.images) }}
			{{ form_errors(form.images) }}

			<ul id="images-fields-list"
				data-prototype="{{ form_widget(form.images.vars.prototype)|e }}"
				data-widget-tags="{{ '<div></div>'|e }}"
				data-widget-counter="{{ form.children|length }}">
				{% for imagesField in form.images %}
					{{ form_errors(imagesField) }}
					{{ form_widget(imagesField) }}
				{% endfor %}
			</ul>
			<a type="button"
					class="btn add-another-collection-widget btn-primary btn-md"
					data-list-selector="#images-fields-list">Ajouter une image</a>
		</div>
		<div class="col">
			{{ form_label(form.videos) }}
			{{ form_errors(form.videos) }}

			<ul id="videos-fields-list"
				data-prototype="{{ form_widget(form.videos.vars.prototype)|e }}"
				data-widget-tags="{{ '<div></div>'|e }}"
				data-widget-counter="{{ form.children|length }}">
				{% for imagesField in form.videos %}
					{{ form_errors(imagesField) }}
					{{ form_widget(imagesField) }}
				{% endfor %}
			</ul>

			<a type="button"
					class="btn add-another-collection-widget-video btn-primary btn-md"
					data-list-selector="#videos-fields-list">Ajouter une vidéo</a>
		</div>
		</div>
	<div class="row">
		<div class="col">
			<button class="btn btn-primary btn-md">{{ button_label|default('Enregistrer') }}</button>

		</div></div>

	</div>
	{{ form_end(form) }}


	<style>
		#trick_category {
			margin-top: 0 !important;
			margin-bottom: 0 !important;
		}
		.form-group {
			display: none;
		}
	</style>

templates/trick/_form_edit.html.twig
{{ form_start(form) }}


<div class="container">
    <div class="row">
        <div class="col">
            {{ form_label(form.name) }}
            {{ form_widget(form.name) }}
            {{ form_errors(form.name) }}
        </div>
        <div class="col">
            {{ form_label(form.category) }}
            {{ form_widget(form.category) }}
            {{ form_errors(form.category) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ form_label(form.description) }}
            {{ form_widget(form.description) }}
            {{ form_errors(form.description) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button class="btn btn-primary btn-md">{{ button_label|default('Enregistrer') }}</button>

        </div></div>

</div>
{{ form_end(form) }}


<style>
    #trick_category {
        margin-top: 0 !important;
        margin-bottom: 0 !important;
    }
    .form-group {
        display: none;
    }
</style>

templates/trick/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Trick{% endblock %}

{% block body %}
    <h1>Edit Trick</h1>

    {{ include('trick/_form_edit.html.twig', {'button_label': 'Update'}) }}


    {{ include('trick/_delete_form.html.twig') }}
{% endblock %}

templates/trick/editFile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Trick{% endblock %}

{% block body %}
    {{ form_start(form) }}


    <div class="container">
        <div class="row">
            <div class="col">
                {{ form_label(form.file) }}
                {{ form_widget(form.file) }}
                {{ form_errors(form.file) }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button class="btn btn-primary btn-md">{{ button_label|default('Enregistrer') }}</button>

            </div></div>

    </div>
    {{ form_end(form) }}


    <style>
        #trick_category {
            margin-top: 0 !important;
            margin-bottom: 0 !important;
        }
        .form-group {
            display: none;
        }
    </style>

{% endblock %}

templates/trick/edit_cover.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Trick{% endblock %}

{% block body %}
{{ form_start(form) }}


<div class="container">
    <div class="row">
        <div class="col">
            {{ form_label(form.cover) }}
            {{ form_widget(form.cover) }}
            {{ form_errors(form.cover) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button class="btn btn-primary btn-md">{{ button_label|default('Enregistrer') }}</button>

        </div></div>

</div>
{{ form_end(form) }}


<style>
    #trick_category {
        margin-top: 0 !important;
        margin-bottom: 0 !important;
    }
    .form-group {
        display: none;
    }
</style>

{% endblock %}

templates/trick/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trick index{% endblock %}

{% block bodyContainer %}
    <div class="headerIndex view full-page-intro">

<h1>SNOWTRICKS</h1>
        <div class="button"></div>
    </div>
    <div class="container-button">

    <div class="container mt-2 pb-5">

        <div class="row mb-4 wow fadeIn trick-container">

        {% for trick in tricks %}
            <!--Grid column-->
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 mb-4">
                <!--Card-->
                    <div class="card">

                        <!--Card image-->
                        <div class="view overlay">
                            <div class="embed-responsive embed-responsive-16by9 rounded-top">
                                    <img class="embed-responsive-item" src="{{asset('/uploads/picture/')}}{{ trick.cover|e }}" >
                            </div>
                        </div>

                        <!--Card content-->
                        <div class="card-body">
                            <!--Title-->
                            <a href="{{ path('trick_show', {'slug': trick.slug}) }}">
                                <h4 class="card-title">{{ trick.name|e }}</h4>
                            <p class="card-text">
                            </p>
                            </a>
                            <p class="card-text">{{ trick.dateCreate ? trick.dateCreate|date('Y-m-d H:i:s') : '' }}</p>
                            {% if app.user == trick.author %}
                                <a href="{{ path('trick_edit', {'slug': trick.slug}) }}"><div class="edit"></div></a>
                                <div class="delete" data-toggle="modal" data-target="#basicExampleModal_{{ trick.id }}"></div>
                            {% endif %}
                            </div>
                    </div>
                <!--/.Card-->

                <!-- Modal -->
                <div class="modal fade" id="basicExampleModal_{{ trick.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel_{{ trick.id }}"
                     aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel_{{ trick.id }}">Supprimer</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Êtes-vous sûr de vouloir supprimer cette figure ?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Retour</button>
                                <form method="post" action="{{ path('trick_delete', {'id': trick.id}) }}">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
                                    <button type="submit" class="btn btn-primary">Supprimer</button>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/ Modal -->


        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </div>
    </div>
        <button type="button" class="btn btn-primary loadMoreAjax">Voir +</button>
        <div class="button2"></div>
    </div>

{% endblock %}

templates/trick/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trick{% endblock %}

{% block body %}

{#    <table class="table">#}
{#        <tbody>#}
{#            <tr>#}
{#                <th>Id</th>#}
{#                <td>{{ trick.id }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Name</th>#}
{#                <td>{{ trick.name }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <th>Date_create</th>#}
{#                <td>{{ trick.dateCreate ? trick.dateCreate|date('Y-m-d H:i:s') : '' }}</td>#}
{#            </tr>#}
{#            #}
{#            <tr>#}
{#                <th>Image</th>#}

{#                <td>{% for key, image in trick.images %} {{ image.name }} <img src="{{asset('uploads/'~image.path)}}"> {% endfor %}</td>#}
{#            </tr>#}

{#        </tbody>#}
{#    </table>#}

    <!--Main layout-->
    <main class="mt-5 pt-5" style="padding-left: 0 !important;" xmlns="http://www.w3.org/1999/html">
        <div class="container">

            <!--Section: Post-->
            <section class="mt-4">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col">

                        <!--Featured Image-->
                        <div class="wow fadeIn text-center col-md-12 mb-3">
                        <img src="{{asset('uploads/picture/'~trick.cover)}}" class="img-fluid z-depth-1" alt="Responsive image">
                            <div class="position-absolute">
                                {% if app.user == trick.author %}
                                    <a href="{{ path('trick_edit_cover', {'slug': trick.slug}) }}"><div class="edit"></div></a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card mb-4 wow fadeIn text-center position-relative">


                                <h1 class="h5 my-4">{{trick.name}}</h1>
                            <div class="container">
                                <div class="row">
                                <div class="col">
                            {% for image in trick.images %}

                                    <img src="{{asset('uploads/picture/'~ image.name)}}" class="img-thumbnail" style="height: 100px; width: 200px;" alt="{{ image.title }}">
                                     <a  class ="btn btn-sm btn-primary" href="{{ path('file_delete', {'id': image.id}) }}">Supprimer</a>

                            {% endfor %}
                                <br>
                                    <a class ="btn btn-sm btn-primary" href="{{ path('add_image', {'id': trick.id}) }}">Ajouter une image</a>
                                    </div>
                                    <div class="col">
                                    {% for video in trick.videos %}
                                        <video controls src="{{asset('uploads/video/'~ video.name)}}" class="img-thumbnail" style="height: 200px; width: 200px;" alt="{{ video.title }}"></video>
                                            <a  class ="btn btn-sm btn-danger" href="{{ path('file_delete', {'id': video.id}) }}">Supprimer la vidéo</a>
                                    {% endfor %}
                                        <a class ="btn btn-sm btn-primary" href="{{ path('add_video', {'id': trick.id}) }}">Ajouter une vidéo</a>

                                    </div>
                            </div>


                        </div>

                        <div class="card mb-4 wow fadeIn text-center">


                        </div>
                        <!--/.Featured Image-->
                        <!--Card-->
                        <div class="card mb-4 wow fadeIn">

                            <!--Card content-->
                            <div class="card-body text-center">
                                    <p>{{trick.description}}</p>
                            </div>

                            <!--Card content-->
                            <div class="card-body">

                                <p class="h6 my-4">{{trick.category.name}}</p>
                                <p class="h6 my-4">Par {{trick.author.email}}, le {{ trick.dateCreate | date('d/m/y') }}</p>
                                {% if app.user == trick.author %}
                                    <a class ="btn btn-sm btn-primary" href="{{ path('trick_edit', {'slug': trick.slug}) }}">modifier</a>
                                {% endif %}
                            </div>

                        </div>
                        <!--/.Card-->

                        <!--Comments-->
                            <div class="card card-comments mb-3 wow fadeIn">

                                <div class="card-header font-weight-bold comment-ajax">{{ compteur }} {% if compteur > 1 %} commentaires {% else %} commentaire {% endif %}</div>
                            </div>

                        <!--/.Comments-->
                            {% if app.user %}
                                {{ form_start(form) }}
                                {{ form_widget(form) }}
                                <button type="submit" class="btn btn-info">Laisser un commentaire</button>
                                {{ form_end(form) }}
                            {% else %}
                                <h3>Veuillez vous connecter pour laisser un commentaire</h3>
                            {% endif %}
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

            </section>
            <!--Section: Post-->

        </div>
    </main>

    {{ include('trick/_delete_form.html.twig') }}
{% endblock %}

{% block javascripts %}
    <script>
    let urlAjaxCommentPost = "{{ path('trick_comment_ajax', {'slug': trick.slug}) }}"
    let trickid = '{{trick.id}}';
    let compteur = {{compteur}};

    </script>
    {{ encore_entry_script_tags('post') }}

{% endblock %}